server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:4399/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: TECHNIQUES_DOCUMENT
  freemarker:
    cache: false #关闭模板缓存
    settings:
      template_update_delay: 0 #检查模板更新延迟时间

logback:
  path: D:/cqlyy/project/cq/cq_practice_techniques_parent/cq_techniques_document/target/